import React from "react";
import "./email.scss";
import { Email, Item, Span, A, Box, renderEmail } from "react-html-email"
import { brotliDecompress } from "zlib";

const emailHTML = renderEmail (
    <div className= "email">
    <Email title="Email Testing">
      <Item align= "center">
        <Span fontSize={20}>This is an Email</Span>
      </Item>
      <Item>
        <Box cellSpacing={20} width="100%" style={{ borderTop: '3px solid black' }}>
          <Item>
            <Span color="gray" lineHeight={20}>Generated by</Span>
            
          </Item>
        </Box>
      </Item>
    </Email>
    </div>
  )
//   const emailHTML = renderEmail (
//     <div className= "email">
//     <Email title="Hello World!">
//         <Item align="center">
//             <Span fontSize={20}>
//                 This is an email;
                
//             </Span>
//         </Item>
//     </Email>
//     </div>
// )




export default emailHTML; 